"""Generate fumadocs-ready MDX reference pages for every plgt command.

Walks the typer app, emits one MDX file per leaf command into ``docs/cli/``.
Subcommands (``plgt configure defaults``) become ``configure-defaults.mdx``.

Hand-authored prose (concept pages, getting-started) lives elsewhere in
``docs/`` and is left alone — only the autogenerated reference pages get
overwritten.
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path
from typing import Any

from typer.main import get_command

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs" / "cli"


def slugify(name: str) -> str:
    """Filename-friendly version of a typer command path."""
    return re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-")


def is_flag_option(param: Any) -> bool:
    """Typer's TyperOption isn't a click.Option subclass — duck-type by .opts."""
    return bool(getattr(param, "opts", None))


def is_positional(param: Any) -> bool:
    return not is_flag_option(param)


def render_option(opt: Any) -> str:
    flags = " / ".join(f"`{o}`" for o in opt.opts)
    if getattr(opt, "secondary_opts", None):
        flags += " / " + " / ".join(f"`{o}`" for o in opt.secondary_opts)
    help_text = (getattr(opt, "help", None) or "").replace("\n", " ").strip() or "—"
    default = ""
    if (
        getattr(opt, "show_default", False)
        and opt.default not in (None, False)
        and not getattr(opt, "is_flag", False)
    ):
        default = f" Default: `{opt.default}`."
    return f"| {flags} | {help_text}{default} |"


def render_argument(arg: Any) -> str:
    required = "required" if getattr(arg, "required", False) else "optional"
    return f"| `{arg.name.upper()}` | {required} positional argument |"


def render_command(cmd: Any, command_path: list[str]) -> str:
    full_name = " ".join(command_path)
    title = f"plgt {full_name}"
    description = (cmd.short_help or cmd.help or "").split("\n")[0].strip().rstrip(".")
    if not description:
        description = f"{title} command."

    body = (cmd.help or "").strip()

    synopsis_parts = [f"plgt {full_name}"]
    for param in cmd.params:
        if is_positional(param):
            tok = f"<{param.name.upper()}>"
            synopsis_parts.append(
                tok if getattr(param, "required", False) else f"[{tok}]"
            )
        elif is_flag_option(param):
            if param.name == "help":
                continue
            primary = param.opts[0]
            if getattr(param, "is_flag", False):
                synopsis_parts.append(f"[{primary}]")
            else:
                metavar = (getattr(param, "metavar", None) or param.type.name).upper()
                synopsis_parts.append(f"[{primary} <{metavar}>]")

    arg_rows = [render_argument(p) for p in cmd.params if is_positional(p)]
    opt_rows = [
        render_option(p)
        for p in cmd.params
        if is_flag_option(p) and not getattr(p, "hidden", False) and p.name != "help"
    ]

    md = [
        "---",
        f'title: "{title}"',
        f'description: "{description}."',
        "---",
        "",
    ]
    if body:
        md += [body, ""]

    md += [
        "## Synopsis",
        "",
        "```bash",
        " ".join(synopsis_parts),
        "```",
        "",
    ]

    if arg_rows:
        md += [
            "## Arguments",
            "",
            "| Argument | Description |",
            "| --- | --- |",
            *arg_rows,
            "",
        ]

    if opt_rows:
        md += [
            "## Options",
            "",
            "| Flag | Description |",
            "| --- | --- |",
            *opt_rows,
            "",
        ]

    return "\n".join(md).rstrip() + "\n"


def walk(cmd: Any, path: list[str]) -> list[tuple[list[str], Any]]:
    children = getattr(cmd, "commands", None)
    if children:
        results: list[tuple[list[str], Any]] = []
        for name, sub in children.items():
            results.extend(walk(sub, [*path, name]))
        return results
    return [(path, cmd)]


def main() -> int:
    from plgt.__main__ import app  # noqa: PLC0415

    root = get_command(app)

    if DOCS_DIR.exists():
        shutil.rmtree(DOCS_DIR)
    DOCS_DIR.mkdir(parents=True)

    pages: list[tuple[str, str]] = []
    for command_path, cmd in walk(root, []):
        if not command_path:
            continue
        slug = slugify("-".join(command_path))
        (DOCS_DIR / f"{slug}.mdx").write_text(render_command(cmd, command_path))
        pages.append((" ".join(command_path), slug))

    index_lines = [
        "---",
        'title: "CLI reference"',
        'description: "All plgt commands."',
        "---",
        "",
        "Generated from the typer app — every leaf command has a page.",
        "",
    ]
    for title, slug in sorted(pages):
        index_lines.append(f"- [`plgt {title}`](./{slug})")
    (DOCS_DIR / "index.mdx").write_text("\n".join(index_lines) + "\n")

    print(f"Wrote {len(pages)} command page(s) to {DOCS_DIR.relative_to(REPO_ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
